#############################################################################
# Makefile for building: qtdetail.app/Contents/MacOS/qtdetail
# Generated by qmake (3.1) (Qt 5.15.2)
# Project:  qtdetail.pro
# Template: app
# Command: /Users/luq/anaconda3/bin/qmake -o qtdetail.mk qtdetail.pro
#############################################################################

MAKEFILE      = qtdetail.mk

EQ            = =

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_CORE_LIB
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -mmacosx-version-min=10.13 -Wall -Wextra -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -mmacosx-version-min=10.13 -Wall -Wextra -fPIC $(DEFINES)
INCPATH       = -I. -I/Users/luq/anaconda3/include/qt -I/Users/luq/anaconda3/include/qt/QtCore -I. -I/Users/luq/anaconda3/mkspecs/macx-clang
QMAKE         = /Users/luq/anaconda3/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/luq/anaconda3/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/luq/anaconda3/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = qtdetail1.0.0
DISTDIR = /Users/luq/dev/projects/ucsc-research/cv-floorplan/PyQt4_gpl_mac-4.12.3/.tmp/qtdetail1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -mmacosx-version-min=10.13 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/Users/luq/anaconda3/lib
LIBS          = $(SUBLIBS) /Users/luq/anaconda3/lib/libQt5Core.dylib   
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = qtdetail.cpp 
OBJECTS       = qtdetail.o
DIST          = /Users/luq/anaconda3/mkspecs/features/spec_pre.prf \
		/Users/luq/anaconda3/mkspecs/qdevice.pri \
		/Users/luq/anaconda3/mkspecs/features/device_config.prf \
		/Users/luq/anaconda3/mkspecs/common/unix.conf \
		/Users/luq/anaconda3/mkspecs/common/mac.conf \
		/Users/luq/anaconda3/mkspecs/common/macx.conf \
		/Users/luq/anaconda3/mkspecs/common/sanitize.conf \
		/Users/luq/anaconda3/mkspecs/common/gcc-base.conf \
		/Users/luq/anaconda3/mkspecs/common/gcc-base-mac.conf \
		/Users/luq/anaconda3/mkspecs/common/clang.conf \
		/Users/luq/anaconda3/mkspecs/common/clang-mac.conf \
		/Users/luq/anaconda3/mkspecs/qconfig.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_3danimation.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_3danimation_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_3dcore.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_3dextras.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_3dinput.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_3dlogic.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_3dquick.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_3drender.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_3drender_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_charts.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_charts_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_core.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_core_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_datavisualization.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_dbus.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_edid_support_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_gamepad.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_gamepad_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_gui.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_help.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_help_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_location.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_location_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_macextras.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_macextras_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_network.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_network_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_networkauth.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_networkauth_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_nfc.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_nfc_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_opengl.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_pdf.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_pdf_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_positioning.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_positioningquick.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_purchasing.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_purchasing_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_qml.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_qmlmodels.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_quick.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_quick3d.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_quick3d_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_quick3drender.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_quick3drender_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_quick3dutils.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_remoteobjects.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_repparser.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_repparser_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_script.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_script_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_scripttools.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_scxml.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_scxml_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_sensors.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_serialbus.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_serialport.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_serialport_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_service_support_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_sql.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_svg.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_testlib.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_texttospeech.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_theme_support_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_uiplugin.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_uitools.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_webchannel.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_webengine.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_webengine_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_webenginecore.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_websockets.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_websockets_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_webview.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_webview_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_widgets.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_xml.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_zlib_private.pri \
		/Users/luq/anaconda3/mkspecs/features/qt_functions.prf \
		/Users/luq/anaconda3/mkspecs/features/qt_config.prf \
		/Users/luq/anaconda3/mkspecs/macx-clang/qmake.conf \
		/Users/luq/anaconda3/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Users/luq/anaconda3/mkspecs/features/exclusive_builds.prf \
		/Users/luq/anaconda3/mkspecs/features/mac/sdk.prf \
		/Users/luq/anaconda3/mkspecs/features/toolchain.prf \
		/Users/luq/anaconda3/mkspecs/features/mac/toolchain.prf \
		/Users/luq/anaconda3/mkspecs/features/default_pre.prf \
		/Users/luq/anaconda3/mkspecs/features/mac/default_pre.prf \
		/Users/luq/anaconda3/mkspecs/features/resolve_config.prf \
		/Users/luq/anaconda3/mkspecs/features/default_post.prf \
		/Users/luq/anaconda3/mkspecs/features/mac/default_post.prf \
		/Users/luq/anaconda3/mkspecs/features/mac/objective_c.prf \
		/Users/luq/anaconda3/mkspecs/features/mac/mac.prf \
		/Users/luq/anaconda3/mkspecs/features/warn_on.prf \
		/Users/luq/anaconda3/mkspecs/features/qt.prf \
		/Users/luq/anaconda3/mkspecs/features/resources_functions.prf \
		/Users/luq/anaconda3/mkspecs/features/resources.prf \
		/Users/luq/anaconda3/mkspecs/features/moc.prf \
		/Users/luq/anaconda3/mkspecs/features/unix/thread.prf \
		/Users/luq/anaconda3/mkspecs/features/qmake_use.prf \
		/Users/luq/anaconda3/mkspecs/features/file_copies.prf \
		/Users/luq/anaconda3/mkspecs/features/mac/rez.prf \
		/Users/luq/anaconda3/mkspecs/features/mac/asset_catalogs.prf \
		/Users/luq/anaconda3/mkspecs/features/testcase_targets.prf \
		/Users/luq/anaconda3/mkspecs/features/exceptions.prf \
		/Users/luq/anaconda3/mkspecs/features/yacc.prf \
		/Users/luq/anaconda3/mkspecs/features/lex.prf \
		qtdetail.pro  qtdetail.cpp
QMAKE_TARGET  = qtdetail
DESTDIR       = 
TARGET        = qtdetail.app/Contents/MacOS/qtdetail

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 13.1
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Applications/Xcode.app/Contents/Developer
EXPORT_VALID_ARCHS = arm64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/luq/dev/projects/ucsc-research/cv-floorplan/PyQt4_gpl_mac-4.12.3/qtdetail.pro


include /Users/luq/anaconda3/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

qtdetail.app/Contents/MacOS/qtdetail:  $(OBJECTS)  
	@test -d qtdetail.app/Contents/MacOS/ || mkdir -p qtdetail.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

qtdetail.mk: qtdetail.pro /Users/luq/anaconda3/mkspecs/macx-clang/qmake.conf /Users/luq/anaconda3/mkspecs/features/spec_pre.prf \
		/Users/luq/anaconda3/mkspecs/qdevice.pri \
		/Users/luq/anaconda3/mkspecs/features/device_config.prf \
		/Users/luq/anaconda3/mkspecs/common/unix.conf \
		/Users/luq/anaconda3/mkspecs/common/mac.conf \
		/Users/luq/anaconda3/mkspecs/common/macx.conf \
		/Users/luq/anaconda3/mkspecs/common/sanitize.conf \
		/Users/luq/anaconda3/mkspecs/common/gcc-base.conf \
		/Users/luq/anaconda3/mkspecs/common/gcc-base-mac.conf \
		/Users/luq/anaconda3/mkspecs/common/clang.conf \
		/Users/luq/anaconda3/mkspecs/common/clang-mac.conf \
		/Users/luq/anaconda3/mkspecs/qconfig.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_3danimation.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_3danimation_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_3dcore.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_3dextras.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_3dinput.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_3dlogic.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_3dquick.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_3drender.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_3drender_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_charts.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_charts_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_core.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_core_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_datavisualization.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_dbus.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_edid_support_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_gamepad.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_gamepad_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_gui.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_help.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_help_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_location.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_location_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_macextras.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_macextras_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_network.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_network_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_networkauth.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_networkauth_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_nfc.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_nfc_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_opengl.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_pdf.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_pdf_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_positioning.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_positioningquick.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_purchasing.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_purchasing_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_qml.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_qmlmodels.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_quick.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_quick3d.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_quick3d_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_quick3drender.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_quick3drender_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_quick3dutils.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_remoteobjects.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_repparser.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_repparser_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_script.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_script_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_scripttools.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_scxml.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_scxml_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_sensors.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_serialbus.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_serialport.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_serialport_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_service_support_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_sql.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_svg.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_testlib.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_texttospeech.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_theme_support_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_uiplugin.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_uitools.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_webchannel.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_webengine.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_webengine_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_webenginecore.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_websockets.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_websockets_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_webview.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_webview_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_widgets.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_xml.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Users/luq/anaconda3/mkspecs/modules/qt_lib_zlib_private.pri \
		/Users/luq/anaconda3/mkspecs/features/qt_functions.prf \
		/Users/luq/anaconda3/mkspecs/features/qt_config.prf \
		/Users/luq/anaconda3/mkspecs/macx-clang/qmake.conf \
		/Users/luq/anaconda3/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Users/luq/anaconda3/mkspecs/features/exclusive_builds.prf \
		/Users/luq/anaconda3/mkspecs/features/mac/sdk.prf \
		/Users/luq/anaconda3/mkspecs/features/toolchain.prf \
		/Users/luq/anaconda3/mkspecs/features/mac/toolchain.prf \
		/Users/luq/anaconda3/mkspecs/features/default_pre.prf \
		/Users/luq/anaconda3/mkspecs/features/mac/default_pre.prf \
		/Users/luq/anaconda3/mkspecs/features/resolve_config.prf \
		/Users/luq/anaconda3/mkspecs/features/default_post.prf \
		/Users/luq/anaconda3/mkspecs/features/mac/default_post.prf \
		/Users/luq/anaconda3/mkspecs/features/mac/objective_c.prf \
		/Users/luq/anaconda3/mkspecs/features/mac/mac.prf \
		/Users/luq/anaconda3/mkspecs/features/warn_on.prf \
		/Users/luq/anaconda3/mkspecs/features/qt.prf \
		/Users/luq/anaconda3/mkspecs/features/resources_functions.prf \
		/Users/luq/anaconda3/mkspecs/features/resources.prf \
		/Users/luq/anaconda3/mkspecs/features/moc.prf \
		/Users/luq/anaconda3/mkspecs/features/unix/thread.prf \
		/Users/luq/anaconda3/mkspecs/features/qmake_use.prf \
		/Users/luq/anaconda3/mkspecs/features/file_copies.prf \
		/Users/luq/anaconda3/mkspecs/features/mac/rez.prf \
		/Users/luq/anaconda3/mkspecs/features/mac/asset_catalogs.prf \
		/Users/luq/anaconda3/mkspecs/features/testcase_targets.prf \
		/Users/luq/anaconda3/mkspecs/features/exceptions.prf \
		/Users/luq/anaconda3/mkspecs/features/yacc.prf \
		/Users/luq/anaconda3/mkspecs/features/lex.prf \
		qtdetail.pro
	$(QMAKE) -o qtdetail.mk qtdetail.pro
/Users/luq/anaconda3/mkspecs/features/spec_pre.prf:
/Users/luq/anaconda3/mkspecs/qdevice.pri:
/Users/luq/anaconda3/mkspecs/features/device_config.prf:
/Users/luq/anaconda3/mkspecs/common/unix.conf:
/Users/luq/anaconda3/mkspecs/common/mac.conf:
/Users/luq/anaconda3/mkspecs/common/macx.conf:
/Users/luq/anaconda3/mkspecs/common/sanitize.conf:
/Users/luq/anaconda3/mkspecs/common/gcc-base.conf:
/Users/luq/anaconda3/mkspecs/common/gcc-base-mac.conf:
/Users/luq/anaconda3/mkspecs/common/clang.conf:
/Users/luq/anaconda3/mkspecs/common/clang-mac.conf:
/Users/luq/anaconda3/mkspecs/qconfig.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_3danimation.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_3danimation_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_3dcore.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_3dcore_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_3dextras.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_3dextras_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_3dinput.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_3dinput_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_3dlogic.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_3dlogic_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_3dquick.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_3dquick_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_3dquickanimation.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_3dquickextras.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_3dquickinput.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_3dquickrender.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_3drender.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_3drender_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_bluetooth.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_bluetooth_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_bodymovin_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_bootstrap_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_charts.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_charts_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_concurrent.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_concurrent_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_core.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_core_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_datavisualization.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_datavisualization_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_dbus.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_dbus_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_edid_support_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_fb_support_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_gamepad.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_gamepad_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_graphics_support_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_gui.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_gui_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_help.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_help_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_location.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_location_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_macextras.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_macextras_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_multimedia.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_multimedia_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_network.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_network_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_networkauth.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_networkauth_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_nfc.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_nfc_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_opengl.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_opengl_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_openglextensions.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_openglextensions_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_pdf.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_pdf_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_pdfwidgets.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_pdfwidgets_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_positioning.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_positioning_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_positioningquick.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_positioningquick_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_printsupport.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_printsupport_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_purchasing.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_purchasing_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_qml.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_qml_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_qmldebug_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_qmlmodels.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_qmltest.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_qmltest_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_quick.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_quick3d.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_quick3d_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_quick3dassetimport.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_quick3drender.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_quick3drender_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_quick3druntimerender.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_quick3dutils.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_quick3dutils_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_quick_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_quickcontrols2.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_quickshapes_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_quicktemplates2.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_quickwidgets.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_remoteobjects.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_repparser.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_repparser_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_script.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_script_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_scripttools.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_scripttools_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_scxml.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_scxml_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_sensors.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_sensors_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_serialbus.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_serialbus_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_serialport.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_serialport_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_service_support_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_sql.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_sql_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_svg.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_svg_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_testlib.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_testlib_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_texttospeech.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_texttospeech_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_theme_support_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_uiplugin.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_uitools.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_uitools_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_webchannel.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_webchannel_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_webengine.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_webengine_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_webenginecore.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_webenginecore_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_webenginewidgets.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_websockets.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_websockets_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_webview.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_webview_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_widgets.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_widgets_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_xml.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_xml_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/Users/luq/anaconda3/mkspecs/modules/qt_lib_zlib_private.pri:
/Users/luq/anaconda3/mkspecs/features/qt_functions.prf:
/Users/luq/anaconda3/mkspecs/features/qt_config.prf:
/Users/luq/anaconda3/mkspecs/macx-clang/qmake.conf:
/Users/luq/anaconda3/mkspecs/features/spec_post.prf:
.qmake.stash:
/Users/luq/anaconda3/mkspecs/features/exclusive_builds.prf:
/Users/luq/anaconda3/mkspecs/features/mac/sdk.prf:
/Users/luq/anaconda3/mkspecs/features/toolchain.prf:
/Users/luq/anaconda3/mkspecs/features/mac/toolchain.prf:
/Users/luq/anaconda3/mkspecs/features/default_pre.prf:
/Users/luq/anaconda3/mkspecs/features/mac/default_pre.prf:
/Users/luq/anaconda3/mkspecs/features/resolve_config.prf:
/Users/luq/anaconda3/mkspecs/features/default_post.prf:
/Users/luq/anaconda3/mkspecs/features/mac/default_post.prf:
/Users/luq/anaconda3/mkspecs/features/mac/objective_c.prf:
/Users/luq/anaconda3/mkspecs/features/mac/mac.prf:
/Users/luq/anaconda3/mkspecs/features/warn_on.prf:
/Users/luq/anaconda3/mkspecs/features/qt.prf:
/Users/luq/anaconda3/mkspecs/features/resources_functions.prf:
/Users/luq/anaconda3/mkspecs/features/resources.prf:
/Users/luq/anaconda3/mkspecs/features/moc.prf:
/Users/luq/anaconda3/mkspecs/features/unix/thread.prf:
/Users/luq/anaconda3/mkspecs/features/qmake_use.prf:
/Users/luq/anaconda3/mkspecs/features/file_copies.prf:
/Users/luq/anaconda3/mkspecs/features/mac/rez.prf:
/Users/luq/anaconda3/mkspecs/features/mac/asset_catalogs.prf:
/Users/luq/anaconda3/mkspecs/features/testcase_targets.prf:
/Users/luq/anaconda3/mkspecs/features/exceptions.prf:
/Users/luq/anaconda3/mkspecs/features/yacc.prf:
/Users/luq/anaconda3/mkspecs/features/lex.prf:
qtdetail.pro:
qmake: FORCE
	@$(QMAKE) -o qtdetail.mk qtdetail.pro

qmake_all: FORCE

qtdetail.app/Contents/PkgInfo: 
	@test -d qtdetail.app/Contents || mkdir -p qtdetail.app/Contents
	@$(DEL_FILE) qtdetail.app/Contents/PkgInfo
	@echo "APPL????" > qtdetail.app/Contents/PkgInfo
qtdetail.app/Contents/Resources/empty.lproj: 
	@test -d qtdetail.app/Contents/Resources || mkdir -p qtdetail.app/Contents/Resources
	@touch qtdetail.app/Contents/Resources/empty.lproj
	
qtdetail.app/Contents/Info.plist: 
	@test -d qtdetail.app/Contents || mkdir -p qtdetail.app/Contents
	@$(DEL_FILE) qtdetail.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.qtdetail,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},com.yourcompany.qtdetail,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.13,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,qtdetail,g" -e "s,@LIBRARY@,qtdetail,g" -e "s,\$${EXECUTABLE_NAME},qtdetail,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" /Users/luq/anaconda3/mkspecs/macx-clang/Info.plist.app >qtdetail.app/Contents/Info.plist

all: qtdetail.mk \
		qtdetail.app/Contents/PkgInfo \
		qtdetail.app/Contents/Resources/empty.lproj \
		qtdetail.app/Contents/Info.plist qtdetail.app/Contents/MacOS/qtdetail

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /Users/luq/anaconda3/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents qtdetail.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r qtdetail.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) qtdetail.mk


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)"

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /Users/luq/anaconda3/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -mmacosx-version-min=10.13 -Wall -Wextra -dM -E -o moc_predefs.h /Users/luq/anaconda3/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean 

####### Compile

qtdetail.o: qtdetail.cpp /Users/luq/anaconda3/include/qt/QtCore/QCoreApplication \
		/Users/luq/anaconda3/include/qt/QtCore/qcoreapplication.h \
		/Users/luq/anaconda3/include/qt/QtCore/qglobal.h \
		/Users/luq/anaconda3/include/qt/QtCore/qconfig-bootstrapped.h \
		/Users/luq/anaconda3/include/qt/QtCore/qconfig.h \
		/Users/luq/anaconda3/include/qt/QtCore/qtcore-config.h \
		/Users/luq/anaconda3/include/qt/QtCore/qsystemdetection.h \
		/Users/luq/anaconda3/include/qt/QtCore/qprocessordetection.h \
		/Users/luq/anaconda3/include/qt/QtCore/qcompilerdetection.h \
		/Users/luq/anaconda3/include/qt/QtCore/qtypeinfo.h \
		/Users/luq/anaconda3/include/qt/QtCore/qsysinfo.h \
		/Users/luq/anaconda3/include/qt/QtCore/qlogging.h \
		/Users/luq/anaconda3/include/qt/QtCore/qflags.h \
		/Users/luq/anaconda3/include/qt/QtCore/qatomic.h \
		/Users/luq/anaconda3/include/qt/QtCore/qbasicatomic.h \
		/Users/luq/anaconda3/include/qt/QtCore/qatomic_bootstrap.h \
		/Users/luq/anaconda3/include/qt/QtCore/qgenericatomic.h \
		/Users/luq/anaconda3/include/qt/QtCore/qatomic_cxx11.h \
		/Users/luq/anaconda3/include/qt/QtCore/qatomic_msvc.h \
		/Users/luq/anaconda3/include/qt/QtCore/qglobalstatic.h \
		/Users/luq/anaconda3/include/qt/QtCore/qmutex.h \
		/Users/luq/anaconda3/include/qt/QtCore/qnumeric.h \
		/Users/luq/anaconda3/include/qt/QtCore/qversiontagging.h \
		/Users/luq/anaconda3/include/qt/QtCore/qstring.h \
		/Users/luq/anaconda3/include/qt/QtCore/qchar.h \
		/Users/luq/anaconda3/include/qt/QtCore/qbytearray.h \
		/Users/luq/anaconda3/include/qt/QtCore/qrefcount.h \
		/Users/luq/anaconda3/include/qt/QtCore/qnamespace.h \
		/Users/luq/anaconda3/include/qt/QtCore/qarraydata.h \
		/Users/luq/anaconda3/include/qt/QtCore/qstringliteral.h \
		/Users/luq/anaconda3/include/qt/QtCore/qstringalgorithms.h \
		/Users/luq/anaconda3/include/qt/QtCore/qstringview.h \
		/Users/luq/anaconda3/include/qt/QtCore/qstringbuilder.h \
		/Users/luq/anaconda3/include/qt/QtCore/qobject.h \
		/Users/luq/anaconda3/include/qt/QtCore/qobjectdefs.h \
		/Users/luq/anaconda3/include/qt/QtCore/qobjectdefs_impl.h \
		/Users/luq/anaconda3/include/qt/QtCore/qlist.h \
		/Users/luq/anaconda3/include/qt/QtCore/qalgorithms.h \
		/Users/luq/anaconda3/include/qt/QtCore/qiterator.h \
		/Users/luq/anaconda3/include/qt/QtCore/qhashfunctions.h \
		/Users/luq/anaconda3/include/qt/QtCore/qpair.h \
		/Users/luq/anaconda3/include/qt/QtCore/qvector.h \
		/Users/luq/anaconda3/include/qt/QtCore/qcontainertools_impl.h \
		/Users/luq/anaconda3/include/qt/QtCore/qpoint.h \
		/Users/luq/anaconda3/include/qt/QtCore/qbytearraylist.h \
		/Users/luq/anaconda3/include/qt/QtCore/qstringlist.h \
		/Users/luq/anaconda3/include/qt/QtCore/qregexp.h \
		/Users/luq/anaconda3/include/qt/QtCore/qstringmatcher.h \
		/Users/luq/anaconda3/include/qt/QtCore/qcoreevent.h \
		/Users/luq/anaconda3/include/qt/QtCore/qscopedpointer.h \
		/Users/luq/anaconda3/include/qt/QtCore/qmetatype.h \
		/Users/luq/anaconda3/include/qt/QtCore/qvarlengtharray.h \
		/Users/luq/anaconda3/include/qt/QtCore/qcontainerfwd.h \
		/Users/luq/anaconda3/include/qt/QtCore/qobject_impl.h \
		/Users/luq/anaconda3/include/qt/QtCore/qeventloop.h \
		/Users/luq/anaconda3/include/qt/QtCore/QFile \
		/Users/luq/anaconda3/include/qt/QtCore/qfile.h \
		/Users/luq/anaconda3/include/qt/QtCore/qfiledevice.h \
		/Users/luq/anaconda3/include/qt/QtCore/qiodevice.h \
		/Users/luq/anaconda3/include/qt/QtCore/QLibraryInfo \
		/Users/luq/anaconda3/include/qt/QtCore/qlibraryinfo.h \
		/Users/luq/anaconda3/include/qt/QtCore/qdatetime.h \
		/Users/luq/anaconda3/include/qt/QtCore/qshareddata.h \
		/Users/luq/anaconda3/include/qt/QtCore/qhash.h \
		/Users/luq/anaconda3/include/qt/QtCore/qversionnumber.h \
		/Users/luq/anaconda3/include/qt/QtCore/QTextStream \
		/Users/luq/anaconda3/include/qt/QtCore/qtextstream.h \
		/Users/luq/anaconda3/include/qt/QtCore/qlocale.h \
		/Users/luq/anaconda3/include/qt/QtCore/qvariant.h \
		/Users/luq/anaconda3/include/qt/QtCore/qmap.h \
		/Users/luq/anaconda3/include/qt/QtCore/qdebug.h \
		/Users/luq/anaconda3/include/qt/QtCore/qset.h \
		/Users/luq/anaconda3/include/qt/QtCore/qcontiguouscache.h \
		/Users/luq/anaconda3/include/qt/QtCore/qsharedpointer.h \
		/Users/luq/anaconda3/include/qt/QtCore/qsharedpointer_impl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtdetail.o qtdetail.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

